<?php

namespace Database\Seeders;

use App\Models\Sls;
use App\Models\Shop;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();
        // Shop::factory(30)->create();

        // User::factory()->withPersonalTeam()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        $users = [
            // ['name' => 'Dr Margaretha Ari Anggorowati, S.Kom, M.T', 'email' => 'm.ari@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Hafti Mardiah, SST, M.Stat.', 'email' => 'hafti@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nunik Sri Rahayu, SST, M.Si.', 'email' => 'nunik.sr@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Dian Kartika Sari, SST, M.Si', 'email' => 'diank@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Susanti Penny Savitri, SST', 'email' => 'penny@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Tri Retno Puspitasari, SST', 'email' => 'pipit.retno@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Grahadian Saukat, SST', 'email' => 'grahadian@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Lita Rosyada, SST', 'email' => 'lita.rosyada@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mardayani, SE', 'email' => 'mardayani@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ari Sugih Mulia, SE., MSE., MA', 'email' => 'ari_sm@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Rahmat Hidayat, S.Si', 'email' => 'rahmat.hidayat@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Resa Surya Utama, SST, M.E', 'email' => 'resa@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Rinaldy, SST', 'email' => 'rinaldy@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Suci Nurmaya Tangkudung, SST', 'email' => 'suci_nt@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Hari Partakoesoema, SST', 'email' => 'hari.parta@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Indrasti Putri Utami Batubara, A.Md', 'email' => 'indrasti@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ruth Yuliani Hutabarat, SST', 'email' => 'ruth.hutabarat@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Reza Vahlevi, SST', 'email' => 'reza.vahlevi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Selvy Ristyandari', 'email' => 'ristya@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Edy Purnomo, S.E.', 'email' => 'edyp@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ismiana Putri, SST', 'email' => 'ismiana.putri@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Elfiona Nathasa Adenanta Ketaren, SST', 'email' => 'elfiona.ketaren@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Candra Kurniawan, SST, M.T', 'email' => 'tjandhra@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Dearossi Hani Khoirunissa, SST, M.SE', 'email' => 'dearossi.hani@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Sinar Wulan Tria Oktalita, S.Tr.Stat.', 'email' => 'sinar.wulan@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Dian Ariyanti', 'email' => 'dian_ariyanti@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Zuhratul Aini, S.Tr.Stat.', 'email' => 'zuhratul.aini@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ruri Alifia Ramadhani, S.Tr.Stat', 'email' => 'ruri.alifia@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Martin Dwi Kristianto, S.Tr.Stat.', 'email' => 'martin.dwik@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Adnan Abdurrahman, SST, M.SE.', 'email' => 'adnan.a@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nita Aprilia, SST, M.M.', 'email' => 'nita.aprilia@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Arif Rachmatillah Amin, S.Tr.Stat.', 'email' => 'arif.ra@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Anis Naufal, S.Tr.Stat.', 'email' => 'anis.naufal@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Myanita Astuti, S.Stat.', 'email' => 'myanita.astuti@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Utary Hafiza, SST', 'email' => 'utary.hafiza@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Oktaviani, S.Tr.Stat.', 'email' => 'oktaviani@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Megita Ritha, S.Tr.Stat.', 'email' => 'megitaritha@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ivan Robi Pratama, S.Tr.Stat.', 'email' => 'ivan.robi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Fenny Afifatul Awwaliyah, S.Tr.Stat.', 'email' => 'fenny.afifatul@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Natasya Afira, S.Tr.Stat.', 'email' => 'natasya.afira@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Wulan Oktaviana, S.E', 'email' => 'wulan.oktaviana@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Satrio Waskitho, S.Tr.Stat.', 'email' => 'satrio.waskitho@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Shafira Purwa Chandra Dewi, A.Md.Stat', 'email' => 'shafira.purwa@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Viki Tria Zianrini, A.Md.Stat.', 'email' => 'viki.tria@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nanda Muliansyah, SST, M.Si.', 'email' => 'nandam@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Donny Cahyo Wibowo, SST, M.Si.', 'email' => 'donny@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Herdinawaty Manurung, S.Psi', 'email' => 'herdina@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Suparto', 'email' => 'suparto@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Wiradinata', 'email' => 'wiradinata@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Haryanti', 'email' => 'haryanti@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Tulus Warman', 'email' => 'tulus@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Tengku Fikri Firdaus', 'email' => 'tengkufikri@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Sofina Anggia, S.P.', 'email' => 'sofina@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Karno, S.T, M.A.', 'email' => 'karno@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Fatimah Suri, S.E.', 'email' => 'fsuri@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Efiandri, S.AP', 'email' => 'efiandri@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Emilia Annisa, SST', 'email' => 'emilia.annisa@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Beti, S.Si, M.Ak.', 'email' => 'beti2@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mery Melinda, SE', 'email' => 'mery.melinda@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Sri Anita, S.Pi', 'email' => 'sri.anita@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Yudi Mustikahadinata, SE.', 'email' => 'yudim@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mardiana Ningsih, S.M.', 'email' => 'mardia@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Hardiansyah, S.Tr.Stat', 'email' => 'hardiansyah@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nia Oktaviani, A.Md', 'email' => 'niaokta-pppk@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Saskia Permata Elzi, A.Md.Kb.N.', 'email' => 'saskia.permata@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Fajar Fatahillah, S.ST, M.Ec.Dev', 'email' => 'fajarf@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Elfira Meirosa', 'email' => 'elfira@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Saor Hasudungan Sitompul, SE', 'email' => 'saor.sitompul@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Irfan Satriadi, S.Si', 'email' => 'irfan.satria@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nana Fitriana, SST', 'email' => 'nana.fitriana@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Daryatno', 'email' => 'daryatno@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Fajar Maulana', 'email' => 'fajarm@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Farikha Fia Fatmawati, S.Tr.Stat', 'email' => 'farikha.fia@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Poernawan Zuhri', 'email' => 'poernawan@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Yudika Simatupang, S.Tr.Stat.', 'email' => 'yudika.simatupang@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Gideon Marpaung, S.Tr.Stat.', 'email' => 'gideon.marpaung@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => "Amir Rifa'i", 'email' => 'amir.rifai@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Muhammad Hafizh Eka Putra, S.Tr.Stat.', 'email' => 'hafizh.eka@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Razali', 'email' => 'razali2@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mohd. Arief Fadillah', 'email' => 'arief.fadillah@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Joko', 'email' => 'joko@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Dino Asmono, S.Ak.', 'email' => 'dino.asmono@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Radhitya Noor Adhyaksani, S.Tr.Stat.', 'email' => 'radhitya.noor@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Agung Tika Wicaksono, S.Tr.Stat', 'email' => 'agung.wicaksono@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Didit Kurniawan, A.Md', 'email' => 'didit@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ardin Feri Syukur Gultom, S.Tr.Stat.', 'email' => 'feri.gultom@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Fathanya Puja Anggaresa, S.Tr.Stat.', 'email' => 'fathanya.puja@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Rahmadathul Wisdawati, A.Md.Stat.', 'email' => 'rahma.wisdawati@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Amoi Sandra Lesmana, A.Md.Stat', 'email' => 'amoi.sandra@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ulil Amri, A.Md.Kom', 'email' => 'ulilamri-pppk@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Jovanka Marya Sitompul, A.Md.Stat.', 'email' => 'jovankamarya@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mutia Hanifah, A.Md.Stat.', 'email' => 'mutiahanifah@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Afysha Diadara, S.Tr.Stat.', 'email' => 'afysha.diadara@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Erlina Nur Syamsiyah, S.Tr.Stat.', 'email' => 'erlinasyamsiyah@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Dicki Prayogi, A.Md.Stat.', 'email' => 'dicki.prayogi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Amyroh Sintia Dewi, A.Md.Stat.', 'email' => 'sintia.dewi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Rizka Mei Wulan, SST', 'email' => 'rizkamei@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nur Ihklas, SST., M.Ec.Dev.', 'email' => 'nur.ikhlas@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Said Alwi, S.E', 'email' => 'said.alwi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Suharmandi', 'email' => 'suharmandi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Supratman', 'email' => 'supratman@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nurwulandari, SST', 'email' => 'nurwulandari@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Muhammad Dikky Miliardi, SST', 'email' => 'mdikky@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Sugiono, S.E.', 'email' => 'sugiono@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Budiyono', 'email' => 'budi.yono@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Christian Putra Ginting, SST', 'email' => 'christian.ginting@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Akmal Ardiansyah Samita, S.E.', 'email' => 'akmal.ardiansyah@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Afifah Rahmah Chania, S.Tr.Stat.', 'email' => 'afifahchania@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'M. Rizki, S.Tr.Stat.', 'email' => 'm.rizki@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mukhlisul Amal Mustofa, S.Tr.Stat.', 'email' => 'amal.mustofa@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nurul Wafiqah Tarihoran, S.Tr.Stat.', 'email' => 'nurultarihoran@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Zicky Zuliyardi, S.E.', 'email' => 'zicky@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'M. Ribawan', 'email' => 'ribawan@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Shela Yulfia Hadist, A.Md.Stat.', 'email' => 'shelayulfia@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Rudy Rusmiady', 'email' => 'rudy.rusmiady@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Zulfikri, A.Md.Stat.', 'email' => 'zul.fikri@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Gloria Stephany Haman Cengga, S.Tr.Stat.', 'email' => 'gloria.stephany@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Jasmine Abqoriyyah Haryanto, S.Tr.Stat.', 'email' => 'jasmineabqor@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Tengku Natasya Auzea Fahyumi, A.Md.Stat.', 'email' => 'tengku.natasya@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Awiskarni, SE, M.M.', 'email' => 'awis@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Krisdiana Galih, SST', 'email' => 'krisdiana.galih@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mikke Janah', 'email' => 'mikke@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Wahyu Dwi Sugianto, SST, M.Si', 'email' => 'wahyu.dwi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'M. Adi Saputra', 'email' => 'adi.saputra@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Saiful', 'email' => 'saiful2@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Lia Oktavera, SST', 'email' => 'oktavera@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Muhamad Andries, SST', 'email' => 'm.andries@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Markum, S.E.', 'email' => 'markum@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Munandar', 'email' => 'nandar@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Fatikha Maulida Izzati, S.Tr.Stat.', 'email' => 'maulida.izzati@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Adisti Fakhrijani Rizqia, S.Tr.Stat.', 'email' => 'adistifakhrijani@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nurmawiya, S.Tr.Stat.', 'email' => 'nurmawiya@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Yully Septia Pertiwi, S.Tr.Stat.', 'email' => 'yully.septia@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ainunnisa Lisaninafi Ah Tanrheeina, S.Tr.Stat.', 'email' => 'ai.tanrheeina@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Josua Reginal Napitupulu, S.Tr.Stat.', 'email' => 'josua.reginal@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Elvira Sellya Hutagalung, S.Tr.Stat.', 'email' => 'elvira.sellya@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Siswodimitro', 'email' => 'dimitro@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Divinia Anjani, A.Md.Stat', 'email' => 'divinia.anjani@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Raja Muhammad Zhickri Pratama, A.Md.Stat.', 'email' => 'raja.pratama@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Bunga Savira Arshella, A.Md.Stat.', 'email' => 'bunga.savira@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Prayoga Yudistyo, A.Md.Stat.', 'email' => 'prayogayudistyo@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ahmad Danang, A.Md.T.', 'email' => 'ahmad.danang@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Neni Marieta Simanjuntak, A.Md', 'email' => 'neni.marieta@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Junita Sholekhatun Safitri, S.Tr.Stat.', 'email' => 'junita.safitri@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Aditya Prameswara Achmadi, S.Tr.Stat.', 'email' => 'aditprameswara@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nuradralena, SST', 'email' => 'nuradralena@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Yuyun Ildatun Nurfa', 'email' => 'ildatun@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Saupi Safari', 'email' => 'saupi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ahmad Chaidir, S.Si', 'email' => 'achaid@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Setia Hadi Putra, SE', 'email' => 'setiahadi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mustapa', 'email' => 'mustapa@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Muhammad Ripani', 'email' => 'mripani@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Tulus Frengky Manullang, S.Tr.Stat.', 'email' => 'tulusfrengky@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Dita Putri Puspitasari, S.Tr.Stat.', 'email' => 'ditaputri@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mia Eka Novita, S.Tr.Stat.', 'email' => 'mia.eka@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Lintang Nirasmara, S.Tr.Stat.', 'email' => 'lintang.nirasmara@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Farah Rachmasari, S.Tr.Stat.', 'email' => 'farah.rachmasari@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Rizki Aji Prasetyo, S.Tr.Stat.', 'email' => 'rizkiaji@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Handigo, S.Tr.Stat.', 'email' => 'handigo@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Gabriel Muhammad Zhafran, S.Tr.Stat.', 'email' => 'gabriel.zhafran@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mewa Azmininovia, A.Md.Stat', 'email' => 'mewa.azmininovia@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Aulia Rahman Sitepu, A.Md.Kom', 'email' => 'auliarahman-pppk@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Feby Vanessa Wandri, A.Md.Stat', 'email' => 'feby.wandri@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Rahmad Kurniadi, A.Md', 'email' => 'rahmad.kurniadi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Tadjie Rifky Ardani, A.Md.Stat.', 'email' => 'tadjie.ardani@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Aulia Salsyafina, A.Md.Stat.', 'email' => 'auliasalsya@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Farah Amalia Nurharisyah, S.Tr.Stat.', 'email' => 'farah.amalia@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Fayza Zaki Asmi Nuraini, S.Tr.Stat.', 'email' => 'fayza.zaki@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Shelin Dina Erliana, S.Tr.Stat.', 'email' => 'shelin.dina@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Steven Fitraeka Setiawan Sanjaya, S.Tr.Stat.', 'email' => 'steven.fitraeka@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Modesty Ulya Mora, A.Md.Stat.', 'email' => 'modesty.ulya@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Thesa Laurantika Gultom, A.Md.Stat.', 'email' => 'thesa.laurantika@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Arief Hidayat, SST', 'email' => 'arief.hidayat@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Adi Cahyadi, SST', 'email' => 'adi.cahyadi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Zurianto Fathur Rachim, S.Tr.Stat.', 'email' => 'fathur.rachim@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Prido Putra Sinaga, S.Tr.Stat.', 'email' => 'prido.sinaga@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Farabi Arsy Edodivano Tauhid, S.Tr.Stat.', 'email' => 'farabi.arsy@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Hafsha Daffa Dhiaulhaq, S.Tr.Stat.', 'email' => 'hafsha.daffa@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Sopo Siahaan, S.Tr.Stat.', 'email' => 'sopo.siahaan@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Fernandus Manurung, A.Md.', 'email' => 'fernandus.manurung@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Fredo Sojuangon Limbong, A.Md.Stat', 'email' => 'fredo.limbong@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Emnur Rahmat, A.Md.Stat.', 'email' => 'emnur.rahmat@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Tiwi Nursafitri, A.Md.Stat.', 'email' => 'tiwi.safitri@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Dedy Elfryady, A.Md', 'email' => 'dedy.elfryady@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Permata Ayunda, A.Md.Stat.', 'email' => 'permataayunda@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Muhammad Rhevanza Kusnadi, A.Md.Stat.', 'email' => 'rhevanza.kusnadi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ervan Nur Rahmat, S.Tr.Stat.', 'email' => 'ervan.nur@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Alya Rudita Priyandini, S.Tr.Stat.', 'email' => 'alya.rudita@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Sinatrya Dwi Purnatadya, S.Tr.Stat.', 'email' => 'sinatrya.dwi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Zahra Ayu Lestari, S.Tr.Stat.', 'email' => 'zahra.ayu@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ronaldo Keristanta Ginting, A.Md.Stat.', 'email' => 'ronaldo.ginting@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ihwanto, S.E.', 'email' => 'ikhwanto@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Eko Aprianto, SST, M.T.I.', 'email' => 'e_aprianto@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Suparyani, SE', 'email' => 'suparyani@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nina Martini', 'email' => 'ninamartini@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Desmaini, S.Si', 'email' => 'desmaini@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Sri Desmiwati, S.ST', 'email' => 'desmi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Adi Darmanto, S.E.', 'email' => 'adi.darmanto@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Maria Lisbetaria Nababan, SST', 'email' => 'lisbet@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Tunggul Hutabarat, SE', 'email' => 'tunggul@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ridha Amalia Hakim, S.Si.', 'email' => 'ridha.hakim@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Florentz Magdalena, SST, M.Sc', 'email' => 'fmagdalena@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Dekha Dwi Harianja, SST', 'email' => 'dekha.harianja@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Adlina Khairunnisa, SST, M.Si.', 'email' => 'adlina.khairunnisa@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Catur Ariadi Wahyono', 'email' => 'caturariadi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Febry Utami, S.Tr.Stat.', 'email' => 'febry.utami@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Anditia Pratiwi, S.Tr.Stat', 'email' => 'anditiapr@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Tania Viona Sirait, S.Tr.Stat.', 'email' => 'viona@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'M. Fadel Pahleva Yacoeb, SST', 'email' => 'fadel.pahleva@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Retza Bahtiar Anugrah, S.Si.', 'email' => 'retza.anugrah@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Evawane Fahma Kusumawardani, S.Tr.Stat', 'email' => 'evawane.fahma@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Moon Bangun Simamora, A.Md, S.E.', 'email' => 'moon@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Metha Arfiandty, A.Md', 'email' => 'metha.arfi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Debora Sinaga, S.E.', 'email' => 'debora.sinaga@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ignatius Aprianto A S, S.Tr.Stat', 'email' => 'ignatius.aprianto@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Renata Putri Henessa, S.Tr.Stat.', 'email' => 'putri.henessa@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ivana Yoselin Purba Siboro, S.Tr.Stat.', 'email' => 'yoselin.purba@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ratih Nurhabibah, S.Tr.Stat.', 'email' => 'ratihnurhabibah@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Arief Tirtana', 'email' => 'arieftirtana@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Moch Yailani', 'email' => 'moch.yailani@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Hardoni', 'email' => 'idon@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Maulidya Fan Ghul Udzan Utami, S.Tr.Stat.', 'email' => 'maulidfan.ghul@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ema Aprilia Fitriani, SST', 'email' => 'emaaprilia@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Reno Fitria, SST', 'email' => 'reno.fitria@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nimta Nababan, S.Mat, M.M.', 'email' => 'nimta@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Sri Fahrina, A.Md.Stat', 'email' => 'sri.fahrina@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Dewi Feronika, A.Md.', 'email' => 'dewifero-pppk@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Cuan Wanti Gultom, A.Md', 'email' => 'cuan.gultom@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Yulia Tri Mardani, S.Si, MA.', 'email' => 'yulia_tri@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Fitri Yadi', 'email' => 'fitri.yadi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Decky Franoza Patria', 'email' => 'decky@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Sudarmanto', 'email' => 'sudarmanto@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Purwo Astono, SST', 'email' => 'astono@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Iman Rahadiansyah, S.Si', 'email' => 'imanrahadiansyah@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Siti Kartini Susilowati, S.S', 'email' => 'skartini@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Olga Srikandi Sinaga, SST', 'email' => 'olgasrikandi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Dian Fitriana Arthati, SST', 'email' => 'dian.fa@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mohamad Nurfajar Kapriaji, SST, M.AP.', 'email' => 'kapriaji.nurfajar@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Dewi Sartika Sari, SST', 'email' => 'dewi.sartika@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Rizka Novalina, SST', 'email' => 'rizka.novalina@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Deasy Dirgantari, S.Tr.Stat', 'email' => 'deasy.dir@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Arlita Gariana, S.Tr.Stat.', 'email' => 'arlita.ga@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Saputra Noviansyah, SST', 'email' => 'saputra.noviansyah@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Albert Assidiq, S.Tr.Stat.', 'email' => 'albert.assidiq@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Vina Astriani, S.Tr.Stat.', 'email' => 'vina.astriani@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Fadhila Annisa Maksum, S.Tr.Stat.', 'email' => 'fadhila.annisa@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Asa Alfan Nahandi, S.Tr.Stat.', 'email' => 'asa.nahandi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Siti Larasati', 'email' => 'larasati2@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Nurul Wahida, A.Md.Stat', 'email' => 'nurul.wahida@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Ardini, A.Md.Stat.', 'email' => 'ardini@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Alfian Rizky Al Majid, S.Tr.Stat.', 'email' => 'alfianrizky@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Afriani Mahardika, SST', 'email' => 'mahardika@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Mardhia Ulfa, A.Md', 'email' => 'mardhia@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            // ['name' => 'Raja Calvina Izumi, A.Md.Kb.N.', 'email' => 'raja.calvina@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Wida Widiastuti S.Si., M.Sc.', 'email' => 'wida_w@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => ' Adam Luthfi Kusumatrisna SST, M.Si.', 'email' => 'adam.luthfi@bps.go.id', 'email_verified_at' => now(), 'password' => Hash::make('password'), 'created_at' => now(), 'updated_at' => now()],
        ];

        foreach ($users as $user) {
            User::create($user);
        };
    }
}
